version: '3.8'

services:
  # Database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: podcast_ai
      POSTGRES_USER: podcast_user
      POSTGRES_PASSWORD: podcast_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U podcast_user -d podcast_ai"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis for Celery
  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # API Gateway
  api-gateway:
    build: ./services/api-gateway
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql://podcast_user:podcast_pass@postgres:5432/podcast_ai
      - REDIS_URL=redis://redis:6379
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      ollama:
        condition: service_started
    volumes:
      - ./services:/app/services
      - ./shared:/app/shared

  # AI Overseer Service
  ai-overseer:
    build: ./services/ai-overseer
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql://podcast_user:podcast_pass@postgres:5432/podcast_ai
      - REDIS_URL=redis://redis:6379
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      ollama:
        condition: service_started
    volumes:
      - ./services:/app/services
      - ./shared:/app/shared

  # News Feed Service
  news-feed:
    build: ./services/news-feed
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql://podcast_user:podcast_pass@postgres:5432/podcast_ai
      - REDIS_URL=redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./services:/app/services
      - ./shared:/app/shared

  # Text Generation Service
  text-generation:
    build: ./services/text-generation
    ports:
      - "8002:8002"
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql://podcast_user:podcast_pass@postgres:5432/podcast_ai
      - REDIS_URL=redis://redis:6379
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      ollama:
        condition: service_started
    volumes:
      - ./services:/app/services
      - ./shared:/app/shared

  # Writer Service
  writer:
    build: ./services/writer
    ports:
      - "8003:8003"
    cpus: "5.0"
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql://podcast_user:podcast_pass@postgres:5432/podcast_ai
      - REDIS_URL=redis://redis:6379
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      ollama:
        condition: service_started
    volumes:
      - ./services:/app/services
      - ./shared:/app/shared

  # Presenter Service
  presenter:
    build: ./services/presenter
    ports:
      - "8004:8004"
    # Allow presenter to use up to 5 CPUs and spawn 5 workers
    cpus: "5.0"
    command: uvicorn main:app --host 0.0.0.0 --port 8004 --workers 5
    user: "0"
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql://podcast_user:podcast_pass@postgres:5432/podcast_ai
      - REDIS_URL=redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./services:/app/services
      - ./shared:/app/shared
      - storage_data:/app/storage

  # Publishing Service
  publishing:
    build: ./services/publishing
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql://podcast_user:podcast_pass@postgres:5432/podcast_ai
      - REDIS_URL=redis://redis:6379
      - LOCAL_STORAGE_PATH=/app/storage
      - LOCAL_SERVER_URL=http://nginx:8080
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      nginx:
        condition: service_started
    volumes:
      - ./services:/app/services
      - ./shared:/app/shared
      - storage_data:/app/storage

  # Local Podcast Host Service
  podcast-host:
    build: ./services/podcast-host
    environment:
      - DATABASE_URL=postgresql://podcast_user:podcast_pass@postgres:5432/podcast_ai
      - LOCAL_STORAGE_PATH=/app/storage
      - LOCAL_SERVER_URL=http://nginx:8080
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./services:/app/services

  # Ollama for local LLM inference
  ollama:
    image: ollama/ollama:latest
    # Allow Ollama to use up to 5 CPUs
    cpus: "5.0"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_ORIGINS=*
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  # Celery Worker
  celery-worker:
    build: ./services/ai-overseer
    command: celery -A app.celery worker --loglevel=info
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql://podcast_user:podcast_pass@postgres:5432/podcast_ai
      - REDIS_URL=redis://redis:6379
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      ollama:
        condition: service_started
    volumes:
      - ./services:/app/services
      - ./shared:/app/shared

  # Celery Beat (Scheduler)
  celery-beat:
    build: ./services/ai-overseer
    command: celery -A app.celery beat --loglevel=info
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql://podcast_user:podcast_pass@postgres:5432/podcast_ai
      - REDIS_URL=redis://redis:6379
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      ollama:
        condition: service_started
    volumes:
      - ./services:/app/services
      - ./shared:/app/shared

  # Nginx for static file serving and proxying
  nginx:
    image: nginx:alpine
    ports:
      - "8090:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - storage_data:/app/storage:ro
    depends_on:
      - podcast-host
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  ollama_data:
  storage_data: